# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Civic Tech Toronto
email: hi@civictech.ca
description: > # this means to ignore newlines until "baseurl:"
  Civic Tech Toronto is bringing together an enthusiastic pack of people, to
  work together, learn together and create civic tech.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://civictech.ca" # the base hostname & protocol for your site
twitter_username: CivicTechTO
github_username: CivicTechTO

gems:
  - octopress-paginate

pagination:
  limit: false

collections:
  - projects

# Build settings
markdown: TwitterKramdown
permalink: pretty

# Ignore files present during Heroku deploy
exclude: ['app.json', 'config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']

# Prose config
org_name: patcon
repo_name: civictechto-jekyll
prose_branch: master
root_url: https://civictechto.herokuapp.com
prose_url: http://prose.io
